### PR TITLE
[REF] Convert to pure Python

### LINKED ISSUE #14: New version for new heudiconv
Heudiconv fixed up multi-echo support a little while ago so we should generate a new version of cis-bidsify.

### LINKED ISSUE #16: Move utility functions to bidsutils
Specifically, I'm talking about `clean_metadata`, `intended_for_gen`, and `complete_jsons`.

### LINKED ISSUE #17: Reorganize into package and make bidsify.py official CLI
We can make bidsify.py/_main a CLI in setup.py.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #14, closes #17, closes #16. The end result of this PR should be that cis-bidsify is written completely in Python.

Still to-do:
1. ~Run bids-validator.~
2. Check minipath (subject- and session-specific output file from heudiconv).

### CODE REVIEW

**Comment by tsalo** [comment]
@adamkimbler I noticed that we don't have a Python equivalent to [this if statement](https://github.com/FIU-Neuro/cis-bidsify/blob/3154e9337724b69e7e9ede19543d5fa35a1d650c/bidsconvert.sh#L39). Do you know if it's necessary?

**Comment by akimbler** [comment]
@tsalo I hate shell scripting. Is that just checking for existence of the path? If so that's easily done with pathlib. If not I have no idea what its doing.

**Comment by tsalo** [comment]
It checks for existence of the `sub-XXX` or `sub-XXX/ses-YYY` folder in the output directory after heudiconv is run. If the folder doesn't exist, then it skips the additional steps (defacing, metadata cleanup, etc.) and writes out to the validator text file that the conversion failed. I wonder, though, if that folder will still be created even if heudiconv fails (in which case, the if/else statement wouldn't catch most failures). I think heudiconv creates the folder after all files are indexed, but before anything is converted. Do you have any thoughts on where failures tend to occur and if the if statement is important?

**Comment by akimbler** [comment]
Yeah, I think we need a better check that isn't contingent on those folders existing. I need to fiddle around with things to check. We're executing  `heudiconv` with `subprocess` right? Wouldn't it be better to check against the exit code of that process for completion?

**Comment by akimbler** [comment]
@tsalo one other thing before merging this PR. I think the traditional way of import from pathlib is `from pathlib import Path` since everything in the package is based on working with the `Path` object. We should probably change to `from pathlib import Path` and replace all instances of `pathlib.Path` with just `Path`, which should help minimize some line length

**Comment by tsalo** [comment]
Merging now.

**Pull request merged**
